# Generated by Django 5.2.5 on 2025-08-16 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "raw_input",
                    models.TextField(help_text="Original free-form todo list input"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(help_text="Duration in minutes"),
                ),
                ("completed", models.BooleanField(default=False)),
                ("schedule_order", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "can_run_parallel",
                    models.BooleanField(
                        default=False,
                        help_text="Can this task run in parallel with others?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dependencies",
                    models.ManyToManyField(
                        blank=True, related_name="dependents", to="tasks.task"
                    ),
                ),
                (
                    "task_list",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="tasks.tasklist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "optimization_algorithm",
                    models.CharField(
                        choices=[
                            ("sequential", "Sequential"),
                            ("parallel", "Parallel Optimization"),
                            ("dependency", "Dependency-Based"),
                        ],
                        default="sequential",
                        max_length=20,
                    ),
                ),
                (
                    "total_estimated_duration",
                    models.PositiveIntegerField(
                        blank=True, help_text="Total duration in minutes", null=True
                    ),
                ),
                (
                    "parallel_blocks",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Groups of tasks that can run in parallel",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="tasks.tasklist",
                    ),
                ),
            ],
        ),
    ]
